HippoCampus/HippoCampus/Controllers/GroupModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HippoCampus.Models;

namespace HippoCampus.Controllers
{
    [Authorize(Roles = "Administrator, Student Worker")]
    public class GroupModelsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public CurrentGroupId groupId;

        // GET: GroupModels
        public ActionResult Index()
        {
            return View(db.Group.ToList());
        }

        // GET: GroupModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GroupModel groupModel = db.Group.Find(id);
            var allWorkers = db.Users.Where(x => x.Roles.Select(role => role.RoleId).Contains("wrkr")).ToList();
            var userGrouped = db.UserGroup.ToList();
            
            var workerGroup = new List<StudentWorkerModel>();
            var studentGroup = new List<InternStudentModel>();

            if (groupModel == null)
            {
                return HttpNotFound();
            }

            foreach (var item in userGrouped)
            {
                if (item.GroupId!=id)
                {
                    userGrouped.Remove(item);
                }
            }

            foreach (var item in userGrouped)
            {
                if (allWorkers.Any(d => d.Id == item.UserId))
                {
                     var studentWorker = db.StudentWorker.Find(item.UserId);
                     workerGroup.Add(studentWorker);
                 }
                 else
                 {
                     var student = db.InternStudentModels.Find(item.UserId);
                     studentGroup.Add(student);
                 }
             }
            
            GroupedUser groupDetailView = new GroupedUser(groupModel.GroupId, groupModel.GroupName, workerGroup, studentGroup);

            return View(groupDetailView);
        }

        // GET: GroupModels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: GroupModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "GroupId,GroupName")] GroupModel groupModel)
        {
            if (ModelState.IsValid)
            {
                db.Group.Add(groupModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(groupModel);
        }

        // GET: GroupModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GroupModel groupModel = db.Group.Find(id);
            if (groupModel == null)
            {
                return HttpNotFound();
            }
            return View(groupModel);
        }

        // POST: GroupModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "GroupId,GroupName")] GroupModel groupModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(groupModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(groupModel);
        }

        // GET: GroupModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GroupModel groupModel = db.Group.Find(id);
            if (groupModel == null)
            {
                return HttpNotFound();
            }
            return View(groupModel);
        }

        // POST: GroupModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            GroupModel groupModel = db.Group.Find(id);
            var groupedUser = db.UserGroup.Where(x => x.GroupId.Equals(id));

            foreach(var user in groupedUser)
            {
                db.UserGroup.Remove(user);
            }

            db.Group.Remove(groupModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //Post:
        
        public ActionResult AddWorker(int id)
        {
            groupId = new CurrentGroupId(id);
            

            GroupModel groupModel = db.Group.Find(id);
            if (groupModel == null)
            {
                return HttpNotFound();
            }
            UngroupWorkerViewModel unGroupWorker = UnGroWorkers(id);
           
            return View(unGroupWorker);
        }

       

        public ActionResult AddWorkerGroup(string Id, int groupId)
        {
            
            UserGroup addWorker = new UserGroup(groupId, Id);
            db.UserGroup.Add(addWorker);
            db.SaveChanges();



            return RedirectToAction("Index");
        }
        

        public ActionResult AddStudent(int id)
        {
            groupId = new CurrentGroupId(id);


            GroupModel groupModel = db.Group.Find(id);
            if (groupModel == null)
            {
                return HttpNotFound();
            }
            UngroupStudentViewModel unGroupWorker = UnGroStudent(id);

            return View(unGroupWorker);
        }



        public ActionResult AddStudentGroup(string Id, int groupId)
        {

            UserGroup addStudent = new UserGroup(groupId, Id);
            db.UserGroup.Add(addStudent);
            db.SaveChanges();



            return RedirectToAction("Index");
        }
       public ActionResult RemoveUserView(string Id, int groupId)
        {
            var user = db.UserGroup.Find(Id);
            db.UserGroup.Remove(user);
            db.SaveChanges();

            return RedirectToAction("Details", new { id = groupId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public UngroupWorkerViewModel UnGroWorkers(int currentGroupID)
        {
            var allWorkers = db.Users.Where(x => x.Roles.Select(role => role.RoleId).Contains("wrkr")).ToList();
            var allGroupMem = db.UserGroup.ToList();
            var unGroupWorker = new List<StudentWorkerModel>();

            if (allGroupMem.Count == 0)
            {
                unGroupWorker = db.StudentWorker.ToList();
            }

            foreach (var worker in allWorkers)
            {
                if (allGroupMem.Any(d => d.UserId.Contains(worker.Id)))
                {
                    
                }
                else
                {
                    var studentWorker = db.StudentWorker.Find(worker.Id);
                    unGroupWorker.Add(studentWorker);
                }
            }
            
            var viewModel = new UngroupWorkerViewModel { GroupId = currentGroupID, UngroupedWorker = unGroupWorker.ToList() };
            return viewModel;
        }

        public UngroupStudentViewModel UnGroStudent(int currentGroupID)
        {
            var allStudent = db.Users.Where(x => x.Roles.Select(role => role.RoleId).Contains("intr")).ToList();
            var allGroupMem = db.UserGroup.ToList();
            var unGroupStudent = new List<InternModel>();

            if (allGroupMem.Count == 0)
            {
                var studnet = db.InternStudentModels.ToList();
                foreach(var stud in studnet)
                {
                    var studModel = new InternModel(stud.intr_stdnt_Id, stud.intr_stdnt_first_name, stud.intr_stdnt_last_name);
                    unGroupStudent.Add(studModel);
                }
            }

            foreach (var s in allStudent)
            {
                if (allGroupMem.Any(d => d.UserId.Contains(s.Id)))
                {
                   
                }
                else
                {
                    var student = db.InternStudentModels.Find(s.Id);
                    var studModel = new InternModel(student.intr_stdnt_Id, student.intr_stdnt_first_name, student.intr_stdnt_last_name);
                    unGroupStudent.Add(studModel);
                }
            }

            var viewModel = new UngroupStudentViewModel { GroupId = currentGroupID, UngroupedStudent = unGroupStudent.ToList() };
            return viewModel;
        }
    }
}

HippoCampus/HippoCampus/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HippoCampus.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            if (User.IsInRole("Administrator") ||
                User.IsInRole("Student Worker"))
            {
                return RedirectToAction("LoginView");
            } 

              
            return View();
        }

        [Authorize(Roles = "Administrator, Student Worker")]
        public ActionResult LoginView()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

HippoCampus/HippoCampus/Controllers/ListModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using HippoCampus.Models;

namespace HippoCampus.Controllers
{
    [Authorize(Roles = "Administrator, Student Worker")]
    public class ListModelsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ListModels
        public ActionResult Index()
        {
            return View(db.ListItem.ToList());
        }

        // GET: ListModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ListItemModel listModel = db.ListItem.Find(id);
            if (listModel == null)
            {
                return HttpNotFound();
            }
            return View(listModel);
        }

        // GET: ListModels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ListModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ListId,ListName,ListLevel,ListDec")] ListItemModel listModel)
        {
            if (ModelState.IsValid)
            {
                if (listModel.ListLevel == "0")
                {
                    listModel.ListLevel = "On Campus";
                }
                else if (listModel.ListLevel == "1")
                {
                    listModel.ListLevel = "Off Campus";
                }
                else if(listModel.ListLevel == "Recommended/Optional")
                {
                    listModel.ListLevel = "Recommended/Optional";
                }

                db.ListItem.Add(listModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(listModel);
        }

        // GET: ListModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ListItemModel listModel = db.ListItem.Find(id);
            if (listModel == null)
            {
                return HttpNotFound();
            }
            return View(listModel);
        }

        // POST: ListModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ListId,ListName,ListLevel,ListDec")] ListItemModel listModel)
        {
            if (ModelState.IsValid)
            {
                if (listModel.ListLevel == "0")
                {
                    listModel.ListLevel = "High";
                }
                else if (listModel.ListLevel == "1")
                {
                    listModel.ListLevel = "Mid";
                }
                else
                {
                    listModel.ListLevel = "Low";
                }

                db.Entry(listModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(listModel);
        }

        // GET: ListModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ListItemModel listModel = db.ListItem.Find(id);
            if (listModel == null)
            {
                return HttpNotFound();
            }
            return View(listModel);
        }

        // POST: ListModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ListItemModel listModel = db.ListItem.Find(id);
            db.ListItem.Remove(listModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HippoCampus/HippoCampus/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<div class="text-center"><h1>About</h1></div>
<main class="container-fluid" style="margin:auto">
    <div class="well col-lg-6 center-item">
        <p>
            The COB’s Executive Masters of Business Administration program
            is making a big impact on the students from China who enroll
            in this yearlong program on the MSU campus. The EMBA, a unique
            cohort-based contract program where students progress through
            curriculum as a group, began in 2007.  Students in this program
            are all Chinese citizens and working professionals with five to
            30 years of experience in their field.  Each student is sponsored
            by his or her home university, current employer or the Chinese government.
            Participation requires one year of full-time study on MSU’s Springfield campus.
            Students take 12 credit hours in the fall and spring semesters and nine credit
            hours in the summer semester.  Courses are taken one at a time over a
            four-week period.  Students generally spend four hours a day in class
            three days a week.
        </p>
    </div>
</main>

HippoCampus/HippoCampus/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact Us";
}
<div class="text-center">
    <h1>Contact</h1>
</div>

<div class="container">
    <div class="col-lg-4 well center-item">
        <p>
            Xiao'ou (Sean) Gong
            COB China Programs Specialist
            <ul class="list-unstyled">
                <li><span class="glyphicon glyphicon-envelope">&nbsp;&nbsp;Xgong@missouristate.edu</span></li>
                <li><span class="glyphicon glyphicon-phone-alt">&nbsp;&nbsp;1-417-350-2423</span></li>
                <li><span class="glyphicon glyphicon-globe">&nbsp;&nbsp;Glass Hall 403</span></li>
            </ul>
        </p>
    </div>
</div>

HippoCampus/HippoCampus/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<a href='@Url.Action("Create", "FutureStudent")'>
    <div id="myCarousel" class="carousel slide" data-ride="carousel" align="center">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
            <li data-target="#myCarousel" data-slide-to="1"></li>
            <li data-target="#myCarousel" data-slide-to="2"></li>
            <li data-target="#myCarousel" data-slide-to="3"></li>
            @*<li data-target="#myCarousel" data-slide-to="4"></li>
            <li data-target="#myCarousel" data-slide-to="5"></li>*@
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">

            <div class="item active">
                <img src="~/images/MoStatePlasterStudentUnion.jpg" alt="Student Union" class="img-responsive">
            </div>

            <div class="item">
                <img src="~/images/RecCenter.jpg" alt="Rec Center" class="img-responsive">
            </div>

            <div class="item">
                <img src="~/images/Pool.jpg" alt="Pool" class="img-responsive">
            </div>
            @*<div class="item">
                <img src="~/images/StrongHall.jpg" alt="Strong Hall" class="img-responsive">
            </div>*@
            <div class="item">
                <img src="~/images/GlassHallThin.jpg" alt="Glass Hall" class="img-responsive">
            </div>
        </div>

        <!-- Left and right controls -->
        <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</a>
    <!-- potato-->

HippoCampus/HippoCampus/Views/Home/LoginView.cshtml
@{
    ViewBag.Title = "LoginView";
}

<div class="jumbotron">YOU ARE LOG IN AS ADMIN OR STUDENT WORKER</div>
<h2>LoginView</h2>


<li>
    <!--This Action Link goes name you want for link, cshtml view you want, in the folder you want to view -->
    @Html.ActionLink("Potential Student Create", "Create", "FutureStudent", new { @class = "element" }, null)
</li>
<li>
    @Html.ActionLink("View/Edit/Delete Student Infomation", "Index", "FutureStudent")
</li>
<li>
    @Html.ActionLink("View/Edit/Delete Activated International Student", "Index", "InternStudent")
</li>
<li>
    @Html.ActionLink("Student Worker List", "Index", "StudentWorker")
</li>
<li>
    @Html.ActionLink("Create Admin User", "RegisterAdmin", "Account")
</li>
<li>
    @Html.ActionLink("Group Index", "Index", "GroupModels")
</li>
<li>
    @Html.ActionLink("List Item", "Index", "ListModels")
</li>